wandb:
  mode: online
  entity: cavendishlabs
  run_tag_prefix: run

dataset:
  path: data/minimax_dataset.pt

experiments:
  seed_count: 5
  runs:
    - name: pretrain_0
      pretrain_steps: 0
    - name: pretrain_20
      pretrain_steps: 20
    - name: pretrain_40
      pretrain_steps: 40
    - name: pretrain_60
      pretrain_steps: 60
    - name: pretrain_80
      pretrain_steps: 80
    - name: pretrain_100
      pretrain_steps: 100

ppo:
  episodes: 4000
  batch_size: 100
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  entropy_coef: 0.01
  value_coef: 0.5
  learning_rate: 0.0001
  update_epochs: 1
  minibatch_size: 64
  eval_interval: 100
  eval_episodes: 200
  eval_minimax_episodes: 200
  reward_ma_window: 50
  opponent: minimax
  log_every_episode: false
  stochastic_eval: true
  model_hidden_dim: 128
  model_heads: 4
  model_depth: 2
  profile_minimax: true

output_root: outputs/pretraining_quick

metrics_output_dir: reports/local_metrics

target_metrics:
  thresholds: [0.80, 0.90, 0.97, 0.99]
  consecutive: 2

ppo_tuning: {}

pretrained:
  directory: checkpoints/pretraining_run
  file_pattern: checkpoint_step_{step:04d}.pt
